id: rel01.0-uc004-benchmark-hello-world
title: Hello World Benchmark

summary: |
  A developer invokes cobbler stitch against a benchmark fixture containing a spec for a
  Hello World Go CLI. Cobbler reads the spec, creates a task in cupboard, builds a prompt
  with full ProjectContext, dispatches Claude in a podman container, and the agent produces a
  working main.go that prints "Hello, World!" to stdout. The orchestrator commits the
  generated code, runs quality gates, and closes the task.

actor: Developer running the benchmark suite or manually testing stitch

trigger: |
  Developer invokes cobbler stitch against a benchmark fixture directory containing a
  specification document describing a Hello World Go CLI.

flow:
  - id: F1
    step: Developer runs cobbler stitch pointing to the benchmark fixture directory
  - id: F2
    step: Cobbler reads the spec document from the fixture directory; the spec describes a Go CLI that prints "Hello, World!" to stdout
  - id: F3
    step: Cobbler creates a task in cupboard with the spec content, task type, and acceptance criteria
  - id: F4
    step: Cobbler claims the task by setting status to in_progress
  - id: F5
    step: The prompt builder constructs a stitch prompt from the template with full ProjectContext YAML blob and execution constitution
  - id: F6
    step: Cobbler invokes Claude Code CLI inside a podman container with the prompt; the container mounts the working directory at the same path
  - id: F7
    step: Claude writes main.go to the fixture output directory
  - id: F8
    step: The orchestrator stages and commits Claude's changes (Claude is forbidden from git)
  - id: F9
    step: The orchestrator records an InvocationRecord with cost, tokens, time, and LOC delta
  - id: F10
    step: The orchestrator saves history artifacts (prompt, log, stats) to the history directory
  - id: F11
    step: On success, cobbler updates the task state to completed; on failure, the task is reset to ready

touchpoints:
  - id: T1
    component: Cupboard
    role: Stores the task; tracks state transitions (ready -> in_progress -> completed)
  - id: T2
    component: Stitch workflow
    role: Claims task, orchestrates prompt-agent-commit workflow
  - id: T3
    component: Context assembly
    role: Builds full ProjectContext YAML blob from project documents
  - id: T4
    component: Prompt builder
    role: Renders stitch.tmpl with StitchPromptData and execution constitution
  - id: T5
    component: Claude invocation
    role: Runs Claude Code CLI in podman container with same-path volume mounting
  - id: T6
    component: History artifacts
    role: Saves prompt, log, and stats YAML per invocation

success_criteria:
  - id: S1
    criterion: Task is created in cupboard and claimed (status transitions to in_progress)
  - id: S2
    criterion: Claude produces main.go in the output directory
  - id: S3
    criterion: go build succeeds with exit code 0
  - id: S4
    criterion: Binary output is exactly "Hello, World!"
  - id: S5
    criterion: Task state is completed in cupboard
  - id: S6
    criterion: InvocationRecord is stored with cost, tokens, and LOC data
  - id: S7
    criterion: History artifacts (prompt, log, stats) exist in the history directory

out_of_scope:
  - Multiple-file applications (main.go only)
  - Test file generation (no main_test.go)
  - Refactoring loops or iterative fixes
  - Agent retry on failure
  - Complex spec parsing or multi-step prompts
