id: rel01.0-uc004-benchmark-hello-world
title: "Use Case: Hello World Benchmark"

summary: |
  A developer invokes cobbler stitch against a benchmark fixture directory
  containing a spec document for a Hello World Go CLI. Cobbler reads the spec,
  creates a task in the cupboard, builds a prompt from templates, dispatches an
  agent, and the agent produces a working main.go that prints "Hello, World!"
  to stdout.

actor: Developer running the benchmark suite or manually testing stitch

trigger: |
  Developer invokes cobbler stitch against a benchmark fixture directory that
  contains a specification document describing a Hello World Go CLI.

flow:
  - F1: "Developer runs cobbler stitch --fixture benchmarks/hello-world."
  - F2: "Cobbler reads the spec document from the fixture directory describing a Go CLI that prints Hello, World! to stdout."
  - F3: "Cobbler creates a crumb in the cupboard representing the code task with spec content, task type coding, and acceptance criteria."
  - F4: "Cobbler claims the crumb by setting its state to taken."
  - F5: "The prompt builder constructs a prompt from templates including the spec, project context, and instructions."
  - F6: "Cobbler dispatches the prompt to the agent via the Agent interface. The agent produces main.go content."
  - F7: "The agent writes main.go to the fixture output directory."
  - F8: "Cobbler runs quality gates: go build on main.go and verifies the binary produces the expected output."
  - F9: "On success, cobbler updates the crumb state to completed. On failure, the crumb state becomes failed with error details."
  - F10: "The benchmark runner reports pass or fail based on the crumb state and gate results."

touchpoints:
  - T1: "Cupboard GetTable(crumbs).Set() and Get() store the code task crumb and track state transitions (prd001-agent-interface R1, prd002-stitch R8)"
  - T2: "Stitch executor Executor.Execute() claims crumb and orchestrates prompt-agent-gate workflow (prd002-stitch R1-R7)"
  - T3: "Prompt builder internal/prompt templates construct prompt from spec and templates (prd002-stitch R4)"
  - T4: "Agent interface Agent.Run() sends prompt to LLM and receives generated code (prd001-agent-interface R1)"
  - T5: "Quality gates go build and output verification validate generated code (prd002-stitch R7)"

success_criteria:
  - S1: "cobbler stitch --fixture benchmarks/hello-world executes without error"
  - S2: "Agent produces main.go in the output directory"
  - S3: "go build -o hello main.go succeeds with exit code 0"
  - S4: "Running ./hello produces stdout containing exactly Hello, World!"
  - S5: "Crumb in the cupboard has state completed"
  - S6: "Benchmark runner reports PASS"

dependencies:
  - D1: "rel01.0-uc001-cupboard-connection — cupboard must be connectable via Go module"
  - D2: "rel01.0-uc003-agent-loop — agent interface and prompt templates must be functional"

risks:
  - RK1: "Agent produces incorrect code; mitigation: quality gates catch failure, spec is simple enough to succeed reliably"
  - RK2: "go build not available in environment; mitigation: document prerequisite Go toolchain installed"
  - RK3: "Output format varies; mitigation: spec explicitly states exact output string in agent prompt"

out_of_scope:
  - Multiple-file applications (main.go only)
  - Test file generation (no main_test.go)
  - Refactoring loops or iterative fixes
  - Agent retry on failure
  - Git worktree management (uses simple output directory)
  - Complex spec parsing or multi-step prompts

test_suite: test-rel01.0
